version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"   # For Jenkins UI
      - "50000:50000" # Optional: for agents
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - jenkins_net

networks:
  jenkins_net:

volumes:
  jenkins_data:
  
